name: build-node-module
description: Build and test a Node.js module.

runs:
    using: "composite"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
      - name: install dependencies
        run: npm ci
        shell: bash
      - name: run linters 
        run: npm run -s lint --if-present
        shell: bash
      - name: build
        run: npm run -s build
        shell: bash
      - name: run tests
        run: npm run -s test -- --reporter tap
        shell: bash
